name: Create and publish docker image

on:
  push:
    branches: 
      - docker-integration

jobs:
  build:
    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1 
      with:
        submodules: true   
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: combo-randomizer/webrandomizer-beta:latest
        username: ${{ secrets.GCR_USERNAME }}
        password: ${{ secrets.GCR_PASSWORD }}
        registry: gcr.io
