name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Use dotnet core 3.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0'
    - name: Run dotnet build
      run: dotnet build -c Release
