name: .NET Core CI Build

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core 3.0.100
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100'
    - name: Run dotnet build
      run: dotnet build -c Release
